// Generated by jextract

package vavi.sound.sc55.jep454;

import java.lang.foreign.Arena;
import java.lang.foreign.FunctionDescriptor;
import java.lang.foreign.Linker;
import java.lang.foreign.MemorySegment;
import java.lang.foreign.SymbolLookup;
import java.lang.invoke.MethodHandle;

public class Mcu extends Mcu$shared {

    Mcu() {
        // Should not be called directly
    }

    static final Arena LIBRARY_ARENA = Arena.ofAuto();

    static final SymbolLookup SYMBOL_LOOKUP;

    static {
        System.loadLibrary("nuked-sc55");
        SYMBOL_LOOKUP = SymbolLookup.loaderLookup().or(Linker.nativeLinker().defaultLookup());
    }


    private static class SC55_postUART {
        public static final FunctionDescriptor DESC = FunctionDescriptor.ofVoid(
            Mcu.C_CHAR
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("SC55_postUART");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * void SC55_postUART(uint8_t data)
     * }
     */
    public static FunctionDescriptor SC55_postUART$descriptor() {
        return SC55_postUART.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * void SC55_postUART(uint8_t data)
     * }
     */
    public static MethodHandle SC55_postUART$handle() {
        return SC55_postUART.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * void SC55_postUART(uint8_t data)
     * }
     */
    public static MemorySegment SC55_postUART$address() {
        return SC55_postUART.ADDR;
    }

    /**
     * {@snippet lang=c :
     * void SC55_postUART(uint8_t data)
     * }
     */
    public static void SC55_postUART(byte data) {
        var mh$ = SC55_postUART.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("SC55_postUART", data);
            }
            mh$.invokeExact(data);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class setenv {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mcu.C_INT,
            Mcu.C_POINTER,
            Mcu.C_POINTER,
            Mcu.C_INT
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.find("setenv").orElseThrow();

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    public static int setenv(MemorySegment name, MemorySegment value, int overwrite) {
        var mh$ = setenv.HANDLE;
        try {
            return (int)mh$.invokeExact(name, value, overwrite);
        } catch (Throwable ex$) {
            throw new AssertionError("should not reach here", ex$);
        }
    }

    private static class SC55_run {
        public static final FunctionDescriptor DESC = FunctionDescriptor.of(
            Mcu.C_INT,
            Mcu.C_INT,
            Mcu.C_POINTER
        );

        public static final MemorySegment ADDR = SYMBOL_LOOKUP.findOrThrow("SC55_run");

        public static final MethodHandle HANDLE = Linker.nativeLinker().downcallHandle(ADDR, DESC);
    }

    /**
     * Function descriptor for:
     * {@snippet lang=c :
     * int SC55_run(int argc, char *argv[])
     * }
     */
    public static FunctionDescriptor SC55_run$descriptor() {
        return SC55_run.DESC;
    }

    /**
     * Downcall method handle for:
     * {@snippet lang=c :
     * int SC55_run(int argc, char *argv[])
     * }
     */
    public static MethodHandle SC55_run$handle() {
        return SC55_run.HANDLE;
    }

    /**
     * Address for:
     * {@snippet lang=c :
     * int SC55_run(int argc, char *argv[])
     * }
     */
    public static MemorySegment SC55_run$address() {
        return SC55_run.ADDR;
    }

    /**
     * {@snippet lang=c :
     * int SC55_run(int argc, char *argv[])
     * }
     */
    public static int SC55_run(int argc, MemorySegment argv) {
        var mh$ = SC55_run.HANDLE;
        try {
            if (TRACE_DOWNCALLS) {
                traceDowncall("SC55_run", argc, argv);
            }
            return (int)mh$.invokeExact(argc, argv);
        } catch (Error | RuntimeException ex) {
           throw ex;
        } catch (Throwable ex$) {
           throw new AssertionError("should not reach here", ex$);
        }
    }
}
